-- MySQL Script generated by MySQL Workbench
-- Thu Mar  4 13:51:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema thingiverse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `thingiverse` ;

-- -----------------------------------------------------
-- Schema thingiverse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `thingiverse` DEFAULT CHARACTER SET utf8 ;
USE `thingiverse` ;

-- -----------------------------------------------------
-- Table `thingiverse`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`profiles` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`profiles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `second_name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `industry` VARCHAR(45) NOT NULL,
  `subindustry` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL DEFAULT "01-01-1910",
  `bio` TINYTEXT NULL COMMENT 'About myself',
  `create_time` DATETIME NOT NULL DEFAULT NOW(),
  `website` VARCHAR(60) NULL COMMENT 'url',
  `cover_photo_id` INT NOT NULL COMMENT 'todo add default cover',
  `avatar_photo_id` INT NOT NULL COMMENT 'todo add default avatar',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`users` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `passwd_hash` VARCHAR(40) NOT NULL COMMENT 'hash of password',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `profiles_id` INT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_users_profiles1_idx` (`profiles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_profiles1`
    FOREIGN KEY (`profiles_id`)
    REFERENCES `thingiverse`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `thingiverse`.`messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`messages` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`messages` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(60) NOT NULL,
  `text` TEXT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  `readed_time` DATETIME NULL,
  `from_users_id` INT NOT NULL,
  `to_users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_users1_idx` (`from_users_id` ASC) VISIBLE,
  INDEX `fk_messages_users2_idx` (`to_users_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_users1`
    FOREIGN KEY (`from_users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_messages_users2`
    FOREIGN KEY (`to_users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`media_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`media_types` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`media_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`media` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`media` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `media_types_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  `size` INT NOT NULL DEFAULT 0,
  `file_path` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `file_path_UNIQUE` (`file_path` ASC) VISIBLE,
  INDEX `fk_media_media_types_idx` (`media_types_id` ASC) VISIBLE,
  INDEX `fk_media_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_media_media_types`
    FOREIGN KEY (`media_types_id`)
    REFERENCES `thingiverse`.`media_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_media_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`forums`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`forums` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`forums` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`groups` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`groups` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `avatar_media_id` INT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  `forums_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_groups_media1_idx` (`avatar_media_id` ASC) VISIBLE,
  INDEX `fk_groups_forums1_idx` (`forums_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_media1`
    FOREIGN KEY (`avatar_media_id`)
    REFERENCES `thingiverse`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_groups_forums1`
    FOREIGN KEY (`forums_id`)
    REFERENCES `thingiverse`.`forums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`followers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`followers` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`followers` (
  `who_id` INT NOT NULL,
  `whom_id` INT NOT NULL,
  INDEX `fk_followers_users1_idx` (`who_id` ASC) VISIBLE,
  INDEX `fk_followers_users2_idx` (`whom_id` ASC) VISIBLE,
  PRIMARY KEY (`who_id`, `whom_id`),
  CONSTRAINT `fk_followers_users1`
    FOREIGN KEY (`who_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_followers_users2`
    FOREIGN KEY (`whom_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`topics`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`topics` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`topics` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id` INT NOT NULL,
  `text` TEXT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  `reply_to_id` INT NULL COMMENT 'Parrent topic if it answer',
  `forums_id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT 'must be only at first topic of thread',
  INDEX `fk_topics_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_topics_topics1_idx` (`reply_to_id` ASC) VISIBLE,
  INDEX `fk_topics_forums1_idx` (`forums_id` ASC) VISIBLE,
  CONSTRAINT `fk_topics_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topics_topics1`
    FOREIGN KEY (`reply_to_id`)
    REFERENCES `thingiverse`.`topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_topics_forums1`
    FOREIGN KEY (`forums_id`)
    REFERENCES `thingiverse`.`forums` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`categories` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`things`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`things` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`things` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `summary` TEXT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  `updated_time` DATETIME NULL,
  `categories_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_things_categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_things_categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `thingiverse`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`comments` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `text` TINYTEXT NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT NOW(),
  `things_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comments_things1_idx` (`things_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_things1`
    FOREIGN KEY (`things_id`)
    REFERENCES `thingiverse`.`things` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`collections`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`collections` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`collections` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_collections_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_collections_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`likes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`likes` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`likes` (
  `things_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  INDEX `fk_likes_things1_idx` (`things_id` ASC) VISIBLE,
  INDEX `fk_likes_users1_idx` (`users_id` ASC) VISIBLE,
  PRIMARY KEY (`things_id`, `users_id`),
  CONSTRAINT `fk_likes_things1`
    FOREIGN KEY (`things_id`)
    REFERENCES `thingiverse`.`things` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`reports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`reports` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`reports` (
  `description` TEXT NOT NULL,
  `topics_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`topics_id`, `users_id`) COMMENT 'One report from one user to one topic',
  INDEX `fk_reports_topics1_idx` (`topics_id` ASC) VISIBLE,
  INDEX `fk_reports_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_reports_topics1`
    FOREIGN KEY (`topics_id`)
    REFERENCES `thingiverse`.`topics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reports_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`things_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`things_files` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`things_files` (
  `things_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  INDEX `fk_things_files_things1_idx` (`things_id` ASC) VISIBLE,
  INDEX `fk_things_files_media1_idx` (`media_id` ASC) VISIBLE,
  PRIMARY KEY (`things_id`, `media_id`),
  CONSTRAINT `fk_things_files_things1`
    FOREIGN KEY (`things_id`)
    REFERENCES `thingiverse`.`things` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_things_files_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `thingiverse`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`comments_media`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`comments_media` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`comments_media` (
  `comments_id` INT NOT NULL,
  `media_id` INT NOT NULL,
  INDEX `fk_comments_media_comments1_idx` (`comments_id` ASC) VISIBLE,
  INDEX `fk_comments_media_media1_idx` (`media_id` ASC) VISIBLE,
  PRIMARY KEY (`comments_id`, `media_id`),
  CONSTRAINT `fk_comments_media_comments1`
    FOREIGN KEY (`comments_id`)
    REFERENCES `thingiverse`.`comments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_media_media1`
    FOREIGN KEY (`media_id`)
    REFERENCES `thingiverse`.`media` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`collections_things`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`collections_things` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`collections_things` (
  `things_id` INT NOT NULL,
  `collections_id` INT NOT NULL,
  INDEX `fk_collections_things_things1_idx` (`things_id` ASC) VISIBLE,
  INDEX `fk_collections_things_collections1_idx` (`collections_id` ASC) VISIBLE,
  PRIMARY KEY (`things_id`, `collections_id`),
  CONSTRAINT `fk_collections_things_things1`
    FOREIGN KEY (`things_id`)
    REFERENCES `thingiverse`.`things` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_collections_things_collections1`
    FOREIGN KEY (`collections_id`)
    REFERENCES `thingiverse`.`collections` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`tags` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`tags` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`users_groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`users_groups` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`users_groups` (
  `users_id` INT NOT NULL,
  `groups_id` INT NOT NULL,
  INDEX `fk_users_groups_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_users_groups_groups1_idx` (`groups_id` ASC) VISIBLE,
  PRIMARY KEY (`users_id`, `groups_id`),
  CONSTRAINT `fk_users_groups_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `thingiverse`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups_groups1`
    FOREIGN KEY (`groups_id`)
    REFERENCES `thingiverse`.`groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `thingiverse`.`things_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `thingiverse`.`things_tags` ;

CREATE TABLE IF NOT EXISTS `thingiverse`.`things_tags` (
  `tags_id` INT NOT NULL,
  `things_id` INT NOT NULL,
  INDEX `fk_things_tags_tags1_idx` (`tags_id` ASC) VISIBLE,
  INDEX `fk_things_tags_things1_idx` (`things_id` ASC) VISIBLE,
  PRIMARY KEY (`tags_id`, `things_id`),
  CONSTRAINT `fk_things_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `thingiverse`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_things_tags_things1`
    FOREIGN KEY (`things_id`)
    REFERENCES `thingiverse`.`things` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
